generate json and png
cartesi/dave pull request #52
Opened 2024-07-05 06:58 UTC by ZzzzHui

2024-07-05 07:11 UTC, ZzzzHui commented
To run, please follow this command https://github.com/cartesi/dave/tree/feature/dave-rollups/prt/lua_poc#run-doom-showcase-with-graphics-on

2 json files (`current-state.json` and `hero-claims.json`) are generated under `prt/lua_poc/utils/`

2 PNG files (the agreed `one.png` and the disagreed `two.png`) are under `prt/lua_poc/snapshots/pixels/`

2024-07-06 03:17 UTC, stephenctw commented
There are some malformed values like `{"value":"äØF­²(Å/+l\u0014HzBé±\u0013}WÏà¾d\u001fï","key":"digest"}]`, can you make sure they are proper hex strings?

2024-07-06 03:35 UTC, stephenctw requested changes

2024-07-06 03:35 UTC, stephenctw commented on prt/lua_poc/utils/current-state.json
> +{"flat_object":{"id":"0xaaab177bf290"},"flat_tables":{"0xaaab178252d0":[{"value":{"id":"0xaaab17821e60"},"key":{"id":"0xaaab177ed7b0"}}],"0xaaab177cded0":[],"0xaaab17834970":[{"value":{"id":"0xaaab17
There are some malformed values like `{"value":"äØF­²�(Å�/+��l\u0014Hz�Bé±\u0013}WÏà¾�d\u001fï�","key":"digest"}]`, can you make sure they are proper hex strings?

2024-07-06 03:35 UTC, stephenctw commented on prt/lua_poc/player/honest_player.lua
> +    -- output hero claims
Can we move this big chuck of code to individual functions? So that the main loop maintains similar structure to the dishonest_player.

```
while true do
    state:fetch()
    local tx_count = sender.tx_count
    local react = honest_strategy:react(state)

    -- prepare files for frontend
    output_tournaments(state)
    output_hero_claim(state)
    pick_2_pngs(state)

    if react then break end
    -- player is considered idle if no tx sent in current iteration
    if tx_count == sender.tx_count then
        helper.log(player_index, "player idling")
        helper.touch_player_idle(player_index)
    else
        helper.rm_player_idle(player_index)
    end
    gc_strategy:react(state)
    time.sleep(5)
end
```

2024-07-06 03:35 UTC, stephenctw commented on prt/lua_poc/doom_showcase/process_doom_graphics.lua
> +local pixels_dir = "/app/snapshots/pixels"
I think we can just use `/app/pixels`, as there will not be snapshots taken anymore.

2024-07-06 03:35 UTC, stephenctw commented on prt/lua_poc/doom_showcase/process_doom_graphics.lua
>  local snapshot_dir = "/app/snapshots"
This can be removed I think.

2024-07-07 12:46 UTC, stephenctw commented
I'd also suggest we remove snapshot feature at:
- https://github.com/cartesi/dave/blob/feature/gen-data/prt/lua_poc/computation/machine.lua#L67-L82
- https://github.com/cartesi/dave/blob/feature/gen-data/prt/lua_poc/computation/commitment.lua#L42
- https://github.com/cartesi/dave/blob/feature/gen-data/prt/lua_poc/computation/commitment.lua#L64

2024-07-08 20:06 UTC, ZzzzHui commented
what about the file `view.sh`, do we still need it

2024-07-08 22:13 UTC, ZzzzHui commented
since we have removed `app/snapshots` folder, now the command to run becomes
```
mkdir -p pixels
docker run --rm \
    --env MACHINE_PATH="/app/lua_poc/program/doom-compute-machine" \
    --env DEPLOY_TO_ANVIL="true" \
    --mount type=bind,source="$(pwd)/pixels",target=/app/pixels \
    dave:latest graphics
```

2024-07-08 22:59 UTC, ZzzzHui commented on prt/lua_poc/utils/current-state.json
> +{"flat_object":{"id":"0xaaab177bf290"},"flat_tables":{"0xaaab178252d0":[{"value":{"id":"0xaaab17821e60"},"key":{"id":"0xaaab177ed7b0"}}],"0xaaab177cded0":[],"0xaaab17834970":[{"value":{"id":"0xaaab17
Will check. in the current file, seems the digest only displays properly for the case that's all 0

2024-07-09 00:58 UTC, stephenctw commented
> what about the file `view.sh`, do we still need it

I think it can be removed as well.

2024-07-09 01:50 UTC, stephenctw commented on prt/lua_poc/utils/current-state.json
> +{"flat_object":{"id":"0xaaab177bf290"},"flat_tables":{"0xaaab178252d0":[{"value":{"id":"0xaaab17821e60"},"key":{"id":"0xaaab177ed7b0"}}],"0xaaab177cded0":[],"0xaaab17834970":[{"value":{"id":"0xaaab17
Maybe you can add a hex() or tostring() to the digest type that does the conversion

2024-07-09 01:58 UTC, stephenctw commented on prt/lua_poc/player/honest_player.lua
> +function pick_2_pngs(state)
Somehow one of the my comment got lost in previous review.

I'd suggest that we let the frontend decide which snapshots it wants to display. As the backend, we provide tournament state, hero state and all the snapshots and their corresponding dispute window. It's up to the frontend on how to visualize those information. What do you think?

2024-07-09 05:03 UTC, ZzzzHui commented on prt/lua_poc/player/honest_player.lua
> +function pick_2_pngs(state)
Yeah we could do that too, although the logic to parse filename and cp would be the same for the frontend.

2024-07-09 09:26 UTC, stephenctw commented on prt/lua_poc/player/honest_player.lua
> +function pick_2_pngs(state)
Please check with Garcia if he agrees on this setting.

2024-07-09 09:32 UTC, stephenctw commented on prt/lua_poc/doom_showcase/process_doom_graphics.lua
> +local machine_settings = { soft_yield = true }
I'd suggest we add `htif = { no_console_putchar = true }` to the machine_settings
So it becomes something like
```
        local machine_settings = { soft_yield = true, htif = { no_console_putchar = true } }
        local machine = cartesi.machine(machine_path, machine_settings)
```
I think this can save us some resources.

And add it to [here](https://github.com/cartesi/dave/blob/feature/gen-data/prt/lua_poc/computation/machine.lua#L47) as well.

2024-07-10 05:54 UTC, ZzzzHui commented on prt/lua_poc/doom_showcase/process_doom_graphics.lua
> +local machine_settings = { soft_yield = true }
thanks stephen. May I ask what `no_console_putchar` means?

2024-07-10 05:55 UTC, ZzzzHui commented on prt/lua_poc/player/honest_player.lua
> +function pick_2_pngs(state)
I have invited him to join the discussions here :)

2024-07-10 06:13 UTC, stephenctw commented on prt/lua_poc/doom_showcase/process_doom_graphics.lua
> +local machine_settings = { soft_yield = true }
This is to tell the emulator to hide console logs of its execution. Like booting Linux, or running DOOM.

2024-07-10 10:44 UTC, jplgarcia commented on prt/lua_poc/player/honest_player.lua
> +function pick_2_pngs(state)
This can be interesting, could feel more lively with every snapshot I could rotate between them.

2024-07-11 08:25 UTC, ZzzzHui commented on prt/lua_poc/utils/current-state.json
> +{"flat_object":{"id":"0xaaab177bf290"},"flat_tables":{"0xaaab178252d0":[{"value":{"id":"0xaaab17821e60"},"key":{"id":"0xaaab177ed7b0"}}],"0xaaab177cded0":[],"0xaaab17834970":[{"value":{"id":"0xaaab17
Hey Stephen, may I ask why we store node digest as binaries? https://github.com/cartesi/dave/blob/9bb10cf5986a83555ff956875441e32dd04925d6/prt/lua_poc/cryptography/hash.lua#L39

2024-07-11 23:16 UTC, ZzzzHui commented
I took an easy path and detect "digest" key and convert its value, during the flatenning phase. So I don't need to mess around with the merkle tree itself

2024-07-12 05:43 UTC, stephenctw commented
This is looking great @ZzzzHui ! @jplgarcia is there anything else you'd like to add or change?

2024-07-12 05:43 UTC, stephenctw approved these changes

2024-07-19 05:39 UTC, merged

2024-07-19 11:29 UTC, guidanoli commented on prt/lua_poc/utils/flat.lua
> +                end
Couldn't this be done before passing down the table to `flatten`?
This has nothing to do with the flattening itself.

2024-07-22 22:55 UTC, ZzzzHui commented on prt/lua_poc/utils/flat.lua
> +                end
yes we could. But it would be the exact same recursions over the same huge tables. Moving this outside will cause code duplication and worse performance, especially that this is run every time honest_player takes an action, and the table grows larger over time.

2024-07-23 02:23 UTC, guidanoli commented on prt/lua_poc/utils/flat.lua
> +                end
Okay, fair enough. :-)

2024-07-23 02:24 UTC, guidanoli commented on prt/lua_poc/utils/flat.lua
> +                end
I mean, we could add a callback parameter, but I agree not to waste too much time on such details.

2024-07-23 03:05 UTC, ZzzzHui commented on prt/lua_poc/utils/flat.lua
> +                end
I did try to move it out and the program runs noticeably much slower, and quite some code repetitions. So let's keep it this way :)